#!/bin/bash

# This is the Phone CleanUp Tool by:
# https://t.me/mtkusbdevice
# https://github.com/mtkusbdevice

CNT="\e[1;36m \e[0m"
COK="\e[1;32m \e[0m"
CER="\e[1;31m \e[0m"
CAT="\e[1;37m \e[0m"
CWR="\e[1;35m \e[0m"
CAC="\e[1;33m \e[0m"

ISADB=/usr/bin/adb
if [ -f "$ISADB" ]; then
    clear
    echo -e "     ___  __                 _______              __  __   ______          __"
    echo -e "    / _ \/ /  ___  ___  ___ / ___/ /__ ___ ____  / / / /__/_  __/__  ___  / /"
    echo -e "   / ___/ _ \/ _ \/ _ \/ -_) /__/ / -_) _ '/ _ \/ /_/ / _ \/ / / _ \/ _ \/ / "
    echo -e "  /_/  /_//_/\___/_//_/\__/\___/_/\__/\_,_/_//_/\____/ .__/_/  \___/\___/_/  "
    echo -e "                                                    /_/                      "

    echo -e "$COK Packages 'android-tools' or 'adb' is installed, moving on."
    sleep 0.3
    echo -e "$CAT Killing the adb server..."
    adb kill-server
    sleep 1
    echo -e "$CNT You are about to execute a script that would attempt to remove bloatware on the Android phones."
    sleep 0.1
    echo -e "$CNT This script WILL NOT run commands that require to be superuser, so DO NOT run it as it."
    sleep 0.1
else 
    echo -e "$CER Packages 'android-tools' or 'adb' was not located, please install it."
    sleep 0.3
    echo -e "$CNT Exiting..."
    exit 
fi

# give the user an option to exit out
read -rep $'\e[1;33m \e[0m Would you like to continue? (Y/N) ' CONTINST
if [[ $CONTINST == "Y" || $CONTINST == "y" ]]; then
    clear
    echo -e "     ___  __                 _______              __  __   ______          __"
    echo -e "    / _ \/ /  ___  ___  ___ / ___/ /__ ___ ____  / / / /__/_  __/__  ___  / /"
    echo -e "   / ___/ _ \/ _ \/ _ \/ -_) /__/ / -_) _ '/ _ \/ /_/ / _ \/ / / _ \/ _ \/ / "
    echo -e "  /_/  /_//_/\___/_//_/\__/\___/_/\__/\_,_/_//_/\____/ .__/_/  \___/\___/_/  "
    echo -e "                                                    /_/                      "
    echo -e " "
    sleep 0.3
    echo -e "\e[1;37m󰒲 \e[0m Waiting for the device..."
    sleep 0.3
    adb wait-for-device
else
    echo -e "$CNT This script will now exit, no changes were made to your phone."
    sleep 1
    exit
fi

sleep 1
echo -e "$COK - Device is connected."
read -rep $'\e[1;33m \e[0m - Start uninstalling? (Y,n) ' CONTUNINST
if [[ $CONTUNINST == "Y" || $CONTUNINST == "y" ]]; then
    echo -e "$COK - Starting...\n"
else
    echo -e "$CNT - This script will now exit, no changes were made to your phone."
    sleep 1
    exit
fi

# echo -e "$CNT Uninstalling 'YouTube'..."
# adb shell pm uninstall --user 0 com.google.android.youtube

echo -e "$CNT Uninstalling 'Meizu Notes'..."
adb shell pm uninstall --user 0 com.meizu.notepaper

echo -e "$CNT Uninstalling 'Duo'/'Meet'..."
adb shell pm uninstall --user 0 com.google.android.apps.tachyon

echo -e "$CNT Uninstalling 'Google Play Music'..."
adb shell pm uninstall --user 0 com.google.android.music

echo -e "$CNT Uninstalling 'Google Drive'..."
adb shell pm uninstall --user 0 com.google.android.apps.docs

echo -e "$CNT Uninstalling 'Google Maps'..."
adb shell pm uninstall --user 0 com.google.android.apps.maps

echo -e "$CNT Uninstalling 'com.android.cellbroadcastreceiver'..."
adb shell pm uninstall --user 0 com.android.cellbroadcastreceiver

# echo -e "$CNT Uninstalling 'Google Chrome'..."
# adb shell pm uninstall --user 0 com.android.chrome

echo -e "$CNT Uninstalling 'Calendar'..."
adb shell pm uninstall --user 0 com.android.calendar

echo -e "$CNT Uninstalling 'Google Play Movies'..."
adb shell pm uninstall --user 0 com.google.android.videos

echo -e "$CNT Uninstalling 'Music'..."
adb shell pm uninstall --user 0 com.meizu.media.music

echo -e "$CNT Uninstalling 'Update'..."
adb shell pm uninstall --user 0 com.meizu.flyme.update

echo -e "$CNT Uninstalling 'Toolbox'..."
adb shell pm uninstall --user 0 com.meizu.flyme.toolbox

# echo -e "$CNT Uninstalling 'Google Photos'..."
# adb shell pm uninstall --user 0 com.google.android.apps.photos

echo -e "$CNT Uninstalling 'Browser'..."
adb shell pm uninstall --user 0 com.android.browser

# echo -e "$CNT Uninstalling 'Gmail'..."
# adb shell pm uninstall --user 0 com.google.android.gm

echo -e "$CNT Uninstalling Meizu's online telemetry services and apps..."
adb shell pm uninstall --user 0 com.meizu.cloud
adb shell pm uninstall --user 0 com.meizu.mzsyncservice
adb shell pm uninstall --user 0 com.meizu.datamigration
adb shell pm uninstall --user 0 com.meizu.flyme.weather
adb shell pm uninstall --user 0 com.meizu.account
adb shell pm uninstall --user 0 com.xrom.intl.appcenter
adb shell pm uninstall --user 0 com.meizu.net.search

echo -e "$CNT Uninstalling 'TouchPal 2017'..."
adb shell pm uninstall --user 0 com.emoji.keyboard.touchpal

sleep 2
echo -e "$CWR And..."
sleep 1
read -rep $'\e[1;33m \e[0m Uninstall Google Play Store and even Google? (Y/N) ' CONTINST
if [[ $CONTINST == "Y" || $CONTINST == "y" ]]; then
    echo -e "$CAT Sure, but you have been warned"
    sleep 1
    echo -e "$CWR Uninstalling 'Google Play Store'..."
    adb shell pm uninstall --user 0 com.android.vending
    echo -e "$CWR Uninstalling 'Google'..."
    adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
    sleep 1
    echo -e "$CNT Rebooting the device..."
    sleep 1
    adb reboot
    sleep 1
    echo -e "$CAT Killing the adb server..."
    adb kill-server
    sleep 1
    echo -e "$COK Script has completed, thanks for using!"
    sleep 1
    echo -e "$CNT Exiting..."
    sleep 1
    exit
else
    sleep 1
    echo -e "$CNT Ok, rebooting the device..."
    sleep 1
    adb reboot
    sleep 1
    echo -e "$CAT Killing the adb server..."
    adb kill-server
    sleep 1
    echo -e "$COK Script has completed, thanks for using!"
    sleep 1
    echo -e "$CNT Exiting..."
    exit
fi